// <auto-generated />
using CleanAPIPJ.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanAPIPJ.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20250114065607_AddPokemonTypeColumnToPokedex")]
    partial class AddPokemonTypeColumnToPokedex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanAPIPJ.Domain.Entities.Pokedex", b =>
                {
                    b.Property<int>("PokemonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PokemonID"));

                    b.Property<string>("PokemonDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PokemonID");

                    b.ToTable("Pokedex");
                });

            modelBuilder.Entity("PokemonType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeID");

                    b.ToTable("PokemonTypes");
                });

            modelBuilder.Entity("PokemonTypeRelation", b =>
                {
                    b.Property<int>("PokemonID")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("PokemonID", "TypeID");

                    b.HasIndex("TypeID");

                    b.ToTable("PokemonTypeRelations");
                });

            modelBuilder.Entity("PokemonTypeRelation", b =>
                {
                    b.HasOne("CleanAPIPJ.Domain.Entities.Pokedex", "Pokedex")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("PokemonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonType", "PokemonType")
                        .WithMany("PokemonRelations")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokedex");

                    b.Navigation("PokemonType");
                });

            modelBuilder.Entity("CleanAPIPJ.Domain.Entities.Pokedex", b =>
                {
                    b.Navigation("PokemonTypes");
                });

            modelBuilder.Entity("PokemonType", b =>
                {
                    b.Navigation("PokemonRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
